/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.AerolineasControlador;
import controlador.AvionControlador;
import controlador.PilotoControlador;
import java.io.FileNotFoundException;
import java.io.IOException;

/**
 *
 * @author adria
 */
public class Vista extends javax.swing.JFrame {

    int fila = 0;
    /**
     * Creates new form vista
     */
    public Vista() {
        initComponents();
    }

    public int getFila() {
        return fila;
    }

    public void setFila(int fila) {
        this.fila = fila;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonCancelarAvion = new javax.swing.JButton();
        txtDNI_piloto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAvion = new javax.swing.JTable();
        jButtonAceptarAvion = new javax.swing.JButton();
        txtModelo = new javax.swing.JTextField();
        txtID_avion = new javax.swing.JTextField();
        jButtonEliminarAvion = new javax.swing.JButton();
        jButtonInsertarAvion = new javax.swing.JButton();
        jButtonModificarAvion = new javax.swing.JButton();
        txtN_asientos = new javax.swing.JTextField();
        txtFecha_fab = new javax.swing.JTextField();
        jCombAviones = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButtonCancelarPiloto = new javax.swing.JButton();
        txtCIF_aerolinea = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePiloto = new javax.swing.JTable();
        jButtonAceptarPiloto = new javax.swing.JButton();
        txtNombrePiloto = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        jButtonEliminarPiloto = new javax.swing.JButton();
        jButtonInsertarPiloto = new javax.swing.JButton();
        jButtonModificarPiloto = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jCombPiloto = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButtonCancelarAerolineas = new javax.swing.JButton();
        txtN_departamentos = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAerolineas = new javax.swing.JTable();
        jButtonAceptarAerolineas = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtCIF = new javax.swing.JTextField();
        jButtonEliminarAerolineas = new javax.swing.JButton();
        jButtonInsertarAerolineas = new javax.swing.JButton();
        jButtonModificarAerolineas = new javax.swing.JButton();
        txtNEmpleados = new javax.swing.JTextField();
        txtSede = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCancelarAvion.setText("Cancelar");

        jTableAvion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "null", "null", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableAvion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAvionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAvion);

        jButtonAceptarAvion.setText("Aceptar");

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        txtID_avion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID_avionActionPerformed(evt);
            }
        });

        jButtonEliminarAvion.setText("Eliminar");

        jButtonInsertarAvion.setText("Insertar");

        jButtonModificarAvion.setText("Modificar");

        jCombAviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombAvionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonInsertarAvion)
                .addGap(29, 29, 29)
                .addComponent(jButtonModificarAvion)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarAvion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAceptarAvion)
                .addGap(8, 8, 8)
                .addComponent(jButtonCancelarAvion)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCombAviones, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtID_avion)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtN_asientos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFecha_fab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDNI_piloto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtID_avion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtN_asientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFecha_fab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDNI_piloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jCombAviones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancelarAvion)
                            .addComponent(jButtonAceptarAvion)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModificarAvion)
                            .addComponent(jButtonInsertarAvion)
                            .addComponent(jButtonEliminarAvion))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Avion", jPanel1);

        jButtonCancelarPiloto.setText("Cancelar");

        jTablePiloto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablePiloto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePilotoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePiloto);

        jButtonAceptarPiloto.setText("Aceptar");

        jButtonEliminarPiloto.setText("Eliminar");

        jButtonInsertarPiloto.setText("Insertar");

        jButtonModificarPiloto.setText("Modificar");

        jCombPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombPilotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButtonInsertarPiloto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModificarPiloto)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarPiloto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(jButtonAceptarPiloto)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelarPiloto))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jCombPiloto, 0, 74, Short.MAX_VALUE))
                                    .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(txtDNI)
                                    .addComponent(txtNombrePiloto))
                                .addComponent(txtCIF_aerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombrePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCIF_aerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jCombPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancelarPiloto)
                            .addComponent(jButtonAceptarPiloto)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModificarPiloto)
                            .addComponent(jButtonInsertarPiloto)
                            .addComponent(jButtonEliminarPiloto))))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 17, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 17, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Piloto", jPanel3);

        jButtonCancelarAerolineas.setText("Cancelar");

        txtN_departamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN_departamentosActionPerformed(evt);
            }
        });

        jTableAerolineas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTableAerolineas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAerolineasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableAerolineas);

        jButtonAceptarAerolineas.setText("Aceptar");
        jButtonAceptarAerolineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarAerolineasActionPerformed(evt);
            }
        });

        jButtonEliminarAerolineas.setText("Eliminar");

        jButtonInsertarAerolineas.setText("Insertar");
        jButtonInsertarAerolineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarAerolineasActionPerformed(evt);
            }
        });

        jButtonModificarAerolineas.setText("Modificar");
        jButtonModificarAerolineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarAerolineasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonInsertarAerolineas)
                .addGap(18, 18, 18)
                .addComponent(jButtonModificarAerolineas)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarAerolineas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAceptarAerolineas)
                .addGap(28, 28, 28)
                .addComponent(jButtonCancelarAerolineas))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCIF, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSede, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN_departamentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtCIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtN_departamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancelarAerolineas)
                            .addComponent(jButtonAceptarAerolineas)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModificarAerolineas)
                            .addComponent(jButtonInsertarAerolineas)
                            .addComponent(jButtonEliminarAerolineas))))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Aerolineas", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtID_avionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID_avionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID_avionActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtN_departamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN_departamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN_departamentosActionPerformed

    private void jTableAerolineasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAerolineasMouseClicked
        
        fila = this.jTableAerolineas.getSelectedRow();
        
        this.txtCIF.setText(AerolineasControlador.listaAerolineas.get(fila).getCIF());
        this.txtNombre.setText((AerolineasControlador.listaAerolineas.get(fila).getNombre()));
        this.txtNEmpleados.setText((AerolineasControlador.listaAerolineas.get(fila).getN_empleados()));
        this.txtSede.setText((AerolineasControlador.listaAerolineas.get(fila).getSede()));
        this.txtN_departamentos.setText((AerolineasControlador.listaAerolineas.get(fila).getN_departamentos()));
    }//GEN-LAST:event_jTableAerolineasMouseClicked

    private void jButtonInsertarAerolineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarAerolineasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInsertarAerolineasActionPerformed

    private void jButtonModificarAerolineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarAerolineasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarAerolineasActionPerformed

    private void jButtonAceptarAerolineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarAerolineasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAceptarAerolineasActionPerformed

    private void jTableAvionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAvionMouseClicked
        this.setFila(this.jTableAvion.getSelectedRow());
        
        this.txtID_avion.setText(AvionControlador.listaAviones.get(fila).getId_avion());
        this.txtModelo.setText(AvionControlador.listaAviones.get(fila).getModelo());
        this.txtN_asientos.setText(AvionControlador.listaAviones.get(fila).getN_asientos());
        this.txtFecha_fab.setText(AvionControlador.listaAviones.get(fila).getFecha_fab());
        this.txtDNI_piloto.setText(AvionControlador.listaAviones.get(fila).getDNI_piloto());
    }//GEN-LAST:event_jTableAvionMouseClicked

    private void jTablePilotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePilotoMouseClicked
        this.setFila(this.jTablePiloto.getSelectedRow());

        this.txtDNI.setText(PilotoControlador.listaPilotos.get(fila).getDNI());
        this.txtNombrePiloto.setText(PilotoControlador.listaPilotos.get(fila).getNombre());
        this.txtApellido.setText(PilotoControlador.listaPilotos.get(fila).getApellido());
        this.txtEdad.setText(PilotoControlador.listaPilotos.get(fila).getEdad());
        this.txtCIF_aerolinea.setText(PilotoControlador.listaPilotos.get(fila).getCIF_Aerolineas());
        
    }//GEN-LAST:event_jTablePilotoMouseClicked

    private void jCombPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombPilotoActionPerformed
        if(this.jCombPiloto.getItemCount()==0){
            this.txtCIF_aerolinea.setText("");
        }
        else
            this.txtCIF_aerolinea.setText(this.jCombPiloto.getSelectedItem().toString());
    }//GEN-LAST:event_jCombPilotoActionPerformed

    private void jCombAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombAvionesActionPerformed
        if(this.jCombAviones.getItemCount()==0){
            this.txtDNI_piloto.setText("");
        }
        else
            this.txtDNI_piloto.setText(this.jCombAviones.getSelectedItem().toString());
    }//GEN-LAST:event_jCombAvionesActionPerformed

    public void cambiarVisibilidadtxfAerolineas(Boolean visible){
        this.txtCIF.setEnabled(visible);
        this.txtNombre.setEnabled(visible);
        this.txtNEmpleados.setEnabled(visible);
        this.txtSede.setEnabled(visible);
        this.txtN_departamentos.setEnabled(visible);
        
    }
    public void cambiarVisibilidadtxfPiloto(Boolean visible){
        this.txtDNI.setEnabled(visible);
        this.txtCIF_aerolinea.setEnabled(visible);
        this.txtNombrePiloto.setEnabled(visible);
        this.txtApellido.setEnabled(visible);
        this.txtEdad.setEnabled(visible);
        this.jCombPiloto.setVisible(visible);
    }
    public void cambiarVisibilidadtxfAvion(Boolean visible){
        this.txtID_avion.setEnabled(visible);
        this.txtModelo.setEnabled(visible);
        this.txtN_asientos.setEnabled(visible);
        this.txtFecha_fab.setEnabled(visible);
        this.txtDNI_piloto.setEnabled(visible);
        this.jCombAviones.setVisible(visible);
    }
    
    
    public void cambiarVisibilidadAerolineasAC(Boolean visible){
        this.jButtonAceptarAerolineas.setEnabled(visible);
        this.jButtonCancelarAerolineas.setEnabled(visible);
        
    }
    public void cambiarVisibilidadPilotoAC(Boolean visible){
        this.jButtonAceptarPiloto.setEnabled(visible);
        this.jButtonCancelarPiloto.setEnabled(visible);
        
    }
    public void cambiarVisibilidadAvionAC(Boolean visible){
        this.jButtonAceptarAvion.setEnabled(visible);
        this.jButtonCancelarAvion.setEnabled(visible);
        
    }
    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     * @throws java.io.FileNotFoundException
     * @throws java.lang.ClassNotFoundException
     */
    public static void main(String args[]) throws IOException, FileNotFoundException, ClassNotFoundException {
       Vista myVista = new Vista();
      
       AerolineasControlador myAerolineasController = new AerolineasControlador(myVista);
       myAerolineasController.insertarAerolineasEnTabla();
       
       PilotoControlador myPilotoController = new PilotoControlador(myVista);
       myPilotoController.insertarPilotosEnTabla();
      
       AvionControlador myAvionController = new AvionControlador(myVista);
       myAvionController.insertarAvionesEnTabla();
       
       myVista.setVisible(true);
       
       myAerolineasController.obtenerPilotoControlador(myPilotoController);
       myPilotoController.obtenerAvionControlador(myAvionController);
       myAvionController.obtenerPilotoControlador(myPilotoController);
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAceptarAerolineas;
    public javax.swing.JButton jButtonAceptarAvion;
    public javax.swing.JButton jButtonAceptarPiloto;
    public javax.swing.JButton jButtonCancelarAerolineas;
    public javax.swing.JButton jButtonCancelarAvion;
    public javax.swing.JButton jButtonCancelarPiloto;
    public javax.swing.JButton jButtonEliminarAerolineas;
    public javax.swing.JButton jButtonEliminarAvion;
    public javax.swing.JButton jButtonEliminarPiloto;
    public javax.swing.JButton jButtonInsertarAerolineas;
    public javax.swing.JButton jButtonInsertarAvion;
    public javax.swing.JButton jButtonInsertarPiloto;
    public javax.swing.JButton jButtonModificarAerolineas;
    public javax.swing.JButton jButtonModificarAvion;
    public javax.swing.JButton jButtonModificarPiloto;
    public javax.swing.JComboBox<String> jCombAviones;
    public javax.swing.JComboBox<String> jCombPiloto;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTableAerolineas;
    public javax.swing.JTable jTableAvion;
    public javax.swing.JTable jTablePiloto;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCIF;
    public javax.swing.JTextField txtCIF_aerolinea;
    public javax.swing.JTextField txtDNI;
    public javax.swing.JTextField txtDNI_piloto;
    public javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txtFecha_fab;
    public javax.swing.JTextField txtID_avion;
    public javax.swing.JTextField txtModelo;
    public javax.swing.JTextField txtNEmpleados;
    public javax.swing.JTextField txtN_asientos;
    public javax.swing.JTextField txtN_departamentos;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombrePiloto;
    public javax.swing.JTextField txtSede;
    // End of variables declaration//GEN-END:variables
}
